public class VariableNamesTheme {

    public static void main(String[] args) {
        System.out.println("\n1. Different Variables");
        int number = 6;
        int digit = 3;
        int sumNumbers = 15;
        int productNumbers = 50;
        int maxNumber = 2_147_483_647;
        int tens = 3;
        double dogWeight = 4.8;
        int originalNumber = 1;
        double percentDeposit = 15.5;
        char ampersand = '&';
        int errorCode = 999;
        int messageType = 22;
        int countZeros = 4;
        int uniqueNumber = 334455;
        int randomNumber = 12345;
        int mathExpression = number / digit;
        int selection = 8;
        int score = 100;
        int maxStringLength = 11;
        int menuItem = 12;
        int costCoffeeToGo = 13;
        int startDate = 1232312;
        int endRange = 24;
        String fullNameEmployeeMonth = "Viktor";
        String ebookTitle = "book";
        int size = 15;
        int capacity = 35;
        int counter = 0;
        String path = "/Users/Documents";
        int countNumbersInLine = 7;
        System.out.println("number = " + number);
        System.out.println("digit = " + digit);
        System.out.println("sumNumber = " + sumNumbers);
        System.out.println("productNumbers = " + productNumbers);
        System.out.println("maxNumber = " + maxNumber);
        System.out.println("tens + " + tens);
        System.out.println("dogWeight = " + dogWeight);
        System.out.println("originalNumber = " + originalNumber);
        System.out.println("percentDeposit = " + percentDeposit);
        System.out.println("ampersand = " + ampersand);
        System.out.println("errorCode = " + errorCode);
        System.out.println("messageType = " + messageType);
        System.out.println("countZeros = " + countZeros);
        System.out.println("uniqueNumber = " + uniqueNumber);
        System.out.println("randomNumber = " + randomNumber);
        System.out.println("mathExpression = " + mathExpression);
        System.out.println("selection = " + selection);
        System.out.println("score = " + score);
        System.out.println("maxStringLength = " + maxStringLength);
        System.out.println("menuItem = " + menuItem);
        System.out.println("costCoffeeToGo = " + costCoffeeToGo);
        System.out.println("startDate = " + startDate);
        System.out.println("endRange = " + endRange);
        System.out.println("fullNameEmployeeMonth = " + fullNameEmployeeMonth);
        System.out.println("ebookTitle = " + ebookTitle);
        System.out.println("size = " + size);
        System.out.println("capacity = " + capacity);
        System.out.println("counter = " + counter);
        System.out.println("path = " + path);
        System.out.println("countNumbersInLine = " + countNumbersInLine);

        System.out.println("\n2. Boolean variables");
        boolean isHundredsEqual = true;
        boolean isComputerOn = true;
        boolean isNumbersEqual = false;
        boolean isCreated = false;
        boolean isEmpty = true;
        boolean isActively = true;
        boolean isNew = false;
        boolean isEmailValid = false;
        boolean isStringsUnique = true;
        System.out.println("isHundredsEqual = " + isHundredsEqual);
        System.out.println("isComputerOn = " + isComputerOn);
        System.out.println("isNumbersEqual = " + isNumbersEqual);
        System.out.println("isCreated = " + isCreated);
        System.out.println("isEmpty = " + isEmpty);
        System.out.println("isActively = " + isActively);
        System.out.println("isNew = " + isNew);
        System.out.println("isEmailValid = " + isEmailValid);
        System.out.println("isStringsUnique = " + isStringsUnique);

        System.out.println("\n3. Abbreviations");
        String uuid = "Universally Unique IDentifier";
        String ram = "Random Access Memory";
        String gb = "Gigabyte";
        String http = "HyperText Transfer Protocol";
        String url = "Uniform Resource Locator";
        String id = "identifier";
        String ascii = "American Standard Code for Information Interchange";
        System.out.println("uuid = " + uuid);
        System.out.println("ram = " + ram);
        System.out.println("gb = " + gb);
        System.out.println("http = " + http);
        System.out.println("url = " + url);
        System.out.println("id = " + id);
        System.out.println("ascii = " + ascii);
    }
}